srobo/docs

- _includes/script.html
- _layouts/default.html
So we can follow how users are using the docs.
> Add Piwik tracking

- _sass/messages.scss
- css/main.scss
> Added error and info box styling

- _includes/footer.html
- programming/python/libraries.md
- programming/sr/vision/markers.md
- user_accounts.md
Fix a selection of broken links
> Broken links

- _sass/docs.scss
> Fix image, table and definition list styling

- IDE/code_checking.md
- IDE/good_commit_messages.md
- index.md
- programming/git_repositories.md
- programming/python/functions.md
- programming/simulator.md
- programming/sr/index.md
- programming/sr/motors/index.md
- programming/sr/power/index.md
- programming/sr/ruggeduinos/custom_firmware.md
- programming/sr/ruggeduinos/index.md
- programming/sr/servos/index.md
- programming/sr/vision/index.md
- troubleshooting/python.md
- tutorials/basic_motor_control.md
- tutorials/python.md
> Fix code highlighting

- _includes/head.html
- _includes/script.html
- _sass/docs.scss
- css/interactive_troubleshooter.css
- js/interactive_troubleshooter.js
- resources/troubleshooter/data.json
- troubleshooting/interactive_troubleshooter.md
> Add missing troubleshooter resources and styling

- programming/simulator.md
- programming/sr/vision/index.md
This appear to have been overlooked at Kickstart, and has [confused competitors in the forums](https://studentrobotics.org/forum/viewtopic.php?f=10&t=168).
> Update vision docs for SR2017

- _sass/docs.scss
- team_admin/user_accounts.md
Update a number of things about the user accounts system and explain how team leader accounts work.
> User account update

- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
A collection of changes (mostly copying from the [website](https://github.com/srobo/website) repo) aimed at making it easier to get going developing this repo.
> Simplify development

- programming/sr/vision/index.md
This is going to conflict horribly with #70, but I'll have to deal with that later.
> Remove mention of old marker types

- team_admin/user_accounts.md
A team was confused by this at the London Kickstart and a team appears to have hit this recently in the forums.
> Clarify what a team leader is

- _includes/sidebar.html
> Fix sidebar not expanding when heading selected.

- kit/assembly.md
- kit/index.md
- programming/python/index.md
Few little fixes and some updates to vision and wire colours 
Resolves #91
> More changes for sr2020

- IDE/code_checking.md
- IDE/good_commit_messages.md
- _includes/footer.html
- kit/index.md
- programming/python/index.md
- programming/simulator.md
- programming/sr/motors/index.md
- team_admin/kit_shipping.md
- tutorials/basic_motor_control.md
- tutorials/python.md
Mostly for moving to HTTPS, though not all.
Suggest looking at the commit messages for the reasons behind each set of changes.
> Update various links

- competition-simulator/programming.md
Resolves https://github.com/srobo/competition-simulator/issues/142
> Sim LED control

- competition-simulator/index.md
https://github.com/srobo/competition-simulator/releases/tag/0.3.2
> Release competition simulator 0.3.2

- competition-simulator/index.md
- programming/python/libraries.md
Following from https://github.com/srobo/competition-simulator/pull/174, this completes the fix to https://github.com/srobo/competition-simulator/issues/163.
> Document the libraries we're committing to providing

- competition-simulator/index.md
Not planning to email for this one, but will post in the forums. I've already update the IDE to use the matching revision.
> Bump the simulator to 0.5.0

- competition-simulator/index.md
Documents https://github.com/srobo/competition-simulator/pull/217.
> Drop older python in simulator

- competition-simulator/index.md
I keep missing the download link for webots when skim reading the page, reword to make it much easier to spot
> improve the scanability of the simulator download.

- simulator/programming/index.md
Competitors from now on won't have Python 2 code to convert.
> No need to mention 2to3 any more

- _data/sidebar_tree.yaml
- team_admin/discord.md
Designed both for reference by competitors and team leaders, as well volunteers.
We don't want to document how to use Discord, just some basics of how ours is setup / should be used.
> Add some basic discord docs

- IDE/code_checking.md
- programming/python/functions.md
- programming/sr/index.md
- programming/sr/power/index.md
- programming/sr/vision/index.md
- troubleshooting/index.md
- troubleshooting/python.md
- tutorials/basic_motor_control.md
- tutorials/python.md
Pretty much what it says. I've tried to keep this to the code examples.
The main things this does:
- drop using module-formatter (`%`) in favour of `str.format`
- used a context manager for file reading
- wrap some `range` calls in `list`; they're ugly now, but at least match the sample outputs
- change to print calls
See individual commit messages for my reasoning.
> Mechanistic modernisation of the Python code examples

- simulator/programming/index.md
> Update simulated robot properties

- simulator/programming/index.md
We removed some other sensors this year, meaning that these pin numbers changed.
> Update the LED pin numberings

- programming/sr/index.md
- programming/sr/vision/index.md
- tutorials/python.md
Couple of small things I missed in #154.
> More python modernisation

- _data/sidebar_tree.yaml
- simulator/programming/index.md
> Clarify simulator programming

- simulator/programming/index.md
There are only 2 pins, not 5.
As noticed by competitor in https://discord.com/channels/775497131057741836/777582218662510612/779725258080387072
> Fix pin location range

- programming/python/libraries.md
Documents the changes made in https://github.com/srobo/competition-simulator/pull/246
> Document newly supported libraries in competition simulator

- simulator/programming/index.md
Update documented distance sensor measurement to be 2m, which is how it is in the simulator.
> Correct distance sensor maximum distance

- simulator/index.md
This year, there are only 2 robots in the arena rather than 4, so adjust the docs to match
> Update docs on controlling other robots with correct number of robots

- simulator/index.md
https://github.com/srobo/competition-simulator/releases/tag/sr2021.2
> Update simulator link for new release

- simulator/index.md
This contains another fix for the distance sensors issue, hopefully this is the last fix we need for this...
There's also a whitespace fix here too, since some bad whitespace seems to have slipped in.
Note: I've not yet actually made the release out of the simulator tag, so the link won't work yet. Obviously we'll need to do that as part of merging this.
> Update the simulator.... again

- simulator/index.md
https://github.com/srobo/competition-simulator/releases/tag/SR2021.4
> Update simulator to SR2021.4

- programming/sr/radio/index.md
Specifically https://github.com/srobo/competition-simulator/pull/299.
> Add docs for a two-stage tower-claim API

- simulator/index.md
https://github.com/srobo/competition-simulator/releases/tag/SR2021.5
> Update simulator link

- simulator/index.md
This includes a fix for biased and excessive noise on the compass.
> Update the simulator to SR2021.10

- _config.yml
- _includes/footer.html
- _includes/head.html
- Add title to the social media icons in the footer
- Update Font Awesome to 4.7
- Change YouTube icon to fit current branding
This is to match the changes of srobo/website#280
> Add LinkedIn and Instagram to footer

- _includes/navigation.html
Link to the sponsor page that was added to the website in https://github.com/srobo/website/pull/283
> Add sponsor link to navigation

- _includes/script.html
See also https://github.com/srobo/website/pull/304
> Replace analytics with Plausible

- .github/workflows/validate.yml
- Rakefile
This is mostly here as a placeholder to get CI working -- I'm going to be adding more validation shortly.
> Add a GitHub Action to validate we can build the site

- _data/sidebar_tree.yaml
- programming/python/libraries.md
> Remove out-of-date simulator pages from sidebar

- programming/sr/power/index.md
Fixes https://github.com/srobo/docs/issues/235
> Update power board docs for SR2022

- programming/sr/ruggeduinos/custom_firmware.md
- programming/sr/ruggeduinos/index.md
> SR2022 Update Ruggeduino docs

- _data/sidebar_tree.yaml
- programming/sr/cheat_sheet.md
> Add SR API Cheat Sheet

- README.md
Fixes https://github.com/srobo/docs/issues/213
> Document where to make changes to the navigation sidebar

- kit/brain_board.md
> Correct Odroid model and remove reference to WiFi

- programming/index.md
- programming/python/functions.md
- programming/python/index.md
> Update outdated references in programming section

- tutorials/python.md
Missed this one in my previous PR
> Update reference to Python 2.6

- troubleshooting/index.md
> Replace references to `sr.robot` in Troubleshooting section

- _config.yml
> Replace kit-support@ email with teams@

- programming/sr/cheat_sheet.md
- programming/sr/index.md
- programming/sr/ruggeduinos/index.md
> Fix ruggeduino referencing and sr module page

- tutorials/basic_motor_control.md
- tutorials/index.md
Fixes https://github.com/srobo/docs/issues/284 and adds some other Python 3 tutorials.
> Python3 tutorials

- programming/sr/motors/index.md
Nit discovered by competitor in Discord.
> Motor power isn't an integer

- _includes/footer.html
- _includes/navigation.html
Related to https://github.com/srobo/website/pull/349
> Replace teams dashboard link with Docs

- kit/motor_board.md
- programming/sr/motors/index.md
This attempts to make the motor board programming docs a bit more accessible for those who may be new to programming.
> Friendlier motor programming docs

- kit/servo_board.md
- programming/sr/servos/index.md
Fixes https://github.com/srobo/docs/issues/317
> Clarify selection of servo outputs

- .dockerignore
- .github/workflows/validate.yml
- Dockerfile
- README.md
- Rakefile
- _config.yml
- docker-compose.yml
This container is only intended for local development!
There's a CI task to ensure the container keeps working, as I think it's the avenue we should recommend for local development.
> Add a docker container for easier local dev

- programming/sr/cheat_sheet.md
- programming/sr/servos/index.md
The V4 servo board doesn't support unpowered servos
> Remove mentions of None from servo docs

- programming/sr/cheat_sheet.md
Fixes https://github.com/srobo/docs/issues/342
> Bootstrap cheat sheet users with API import

- _config.yml
- _includes/footer.html
- _includes/head.html
- _includes/navigation.html
- _sass/footer.scss
This essentially applies https://github.com/srobo/website/pull/360 and any other recent changes.
Fixes https://github.com/srobo/docs/issues/327
> Sync the site footer with the main website

- kit/servo_board.md
Fixes https://github.com/srobo/docs/issues/101 (from which it also draws its information).
Reviewer: please consider whether the terminology here is useful/correct; I've essentially made it up as I don't know what to call this.
> Document the Servo Board control scheme and specifications

- programming/python/index.md
- tutorials/python.md
This doesn't touch the simulator, which will need a separate release to make this change.
I've skimmed through all the code examples and didn't spot anything which needed updating.
Fixes https://github.com/srobo/docs/issues/346
> Update physical kit mentions of Python version to 3.10

- programming/sr/vision/index.md
All current versions of the robot API now have this feature.
Fixes https://github.com/srobo/docs/issues/367
> Remove obsolete version info box

- programming/sr/power/index.md
> Update `buzz` docs

- programming/sr/leds/index.md
> Update KCH interface

- _sass/common.scss
- kit/assembly.md
> Update kit assembly video

- resources/troubleshooter/data.json
Link to the Discord docs rather than the forums
> Update support links in the interactive troubleshooter

- tutorials/microgames.md
Update the microgames link to link to https://srobo.org/microgames
> Update microgames link

- programming/sr/leds/index.md
LEDs are controlled on a `.leds` attribute
https://github.com/srobo/sr-robot3/blob/36873cb157d87c6357d5e433d16bcffbfed90d73/sr/robot3/kch.py#L98
> Fix KCH LED docs

- simulator/programming/index.md
and the limitations of the API.
> Document that the simulated robot has a camera

- .spelling
- _data/sidebar_tree.yaml
- kit/brain_board/advanced.md
~This page is intentionally hidden from the sidebar menu. We will send a link to Students if they need the information. This is to avoid confusing students who don't want to hack around with the kit.~
> Add an advanced page for the Brain Board

- _data/kit_versions.yml
- ~Change base to master once #414 is merged~
- Marked as draft until image is ready.
> Release SR2023.1.0 kit software

- simulator/index.md
These were already listed on the site, but the cross linking paragraph had been removed in SR2022.
As we have them again they're worth a mention.
> Mention the libraries available in the simulator

- simulator/index.md
See https://github.com/srobo/competition-simulator/releases/tag/sr2023.2 for the changes this brings.
> Bump the simulator to sr2023.2

- resources/kit/ruggeduino-fw.ino
Comment in arduino fw says power board, that is wrong
> Fix error in ruggeduino fw comment

- .spelling
- programming/python/libraries.md
- programming/sr/vision/index.md
> Remove references to Zoloto

- simulator/index.md
This adds support for Webots R2023a.
Closes #438.
> Bump the simulation to sr2023.3

- simulator/programming/index.md
This is lifted from the examples in https://github.com/srobo/competition-simulator#running-webots
> Document how to run robot code in different corners

- programming/sr/vision/index.md
Fixes https://github.com/srobo/docs/issues/374.
> Robot.camera.save doesn't return a value

- simulator/index.md
Mention the version of the simulator and its release date, alongside the download link.  This is so students can tell if a new version is available before downloading the zip or finding the updates section.
> Mention simulator version and release date

- programming/sr/ruggeduinos/custom_firmware.md
Adds documentation to clarify the effects of  https://github.com/srobo/j5/issues/882 for this year's competition.
> Add warning about setting up pins in custom firmware

- kit/servo_board.md
Aux power details
Simplify servo explaination
Update timing numbers to match new FW
> SR2024 - Update Section - Servo board

- programming/leds.md
- Update KCH to match new API
- Standardize on "KCH board" or just "KCH" naming
- Readability
- Clarity
> SR2024 - Update Section - Brain board LEDs

- kit/arduino.md
Update the content on the arduino page
- clarity
- readability
- changed from using ruggeduino to arduino
Will create a seperate issue about rehosting the resources at the bottom of the page
> SR2024 - Update Section - Arduino

- Rakefile
- _config.yml
- _dev.yml
- _includes/script.html
This is mostly copied over form the website.
> Make user-tracking optional

- programming/power.md
update to match new API
Update for clarity
> SR2024 - Update Section - Power board API

- programming/motors.md
- Update with new features
- Increase clarity
> SR2024 - Update Section - Motor board API

- programming/sr/cheat_sheet.md
- programming/sr/vision/index.md
Based on a previous patch which Dan put together (https://github.com/srobo/docs/pull/415), updated and with some fixes applied.
> Mention the 'frame' argument to the vision API

- programming/servos.md
Extended servo range.
Remove index boards by serial as they only have one board.
> SR2024 - Update Section - Servo board API

- programming/vision/index.md
fix typo in vision code snippet
> Fix vision code typo

- _data/sidebar_tree.yaml
- kit/index.md
Update top level kit page, removed all dead links
> SR2024 - Update Section - Kit

- index.md
> SR2024 - Update Section - Introduction

- kit/brain_board/wifi.md
> remove references to print wifi creds

- kit/batteries/index.md
Update the page formatting to use markdown instead of html bits
> battery page markdown formatting

- programming/robot_api/comp_mode.md
- programming/robot_api/index.md
- Update the top level robot API page
- Add a page about the specifics of comp mode
Would specifically like some input on the page explaining comp mode
> SR2024 - Update Section - Robot API

- programming/index.md
Top level page to the programming section
Links to some other pages and python tutorials
> SR2024 - Update Section - Programming

- .spelling
- _data/sidebar_tree.yaml
- programming/arduino/custom_firmware.md
- programming/arduino/extended_sr_firmware.md
- programming/arduino/index.md
- programming/arduino/sr_firmware.md
- resources/kit/arduino-fw.ino
Update the Arduino API section to be more clear and update custom arduino section to match the new implimentation
> SR2024 - Update Section - Arduino API

- kit/batteries/hke4_charger.md
- kit/batteries/index.md
Update guidance on not leaving batteries on 0% or 100%
> SR2024 - Update Section - Batteries

- programming/vision/index.md
- programming/vision/position.md
jpg is faster than png
round numbers because simpler
> Jdp vision page tweaks

- kit/index.md
> Document battery charger barrel size

- programming/vision/index.md
> change to use jpg instead of png

- competitor_resources/microgames.md
- kit/brain_board/python_libraries.md
- kit/brain_board/robot_os.md
- kit/brain_board/web_interface.md
- programming/arduino/custom_firmware.md
- programming/arduino/index.md
- programming/cheat_sheet.md
- programming/index.md
- programming/leds.md
- programming/motors.md
- programming/power.md
- programming/robot_api/index.md
- programming/servos.md
- programming/vision/index.md
- programming/vision/markers.md
- rules/safety_regulations.md
- simulator/simulator_programming.md
- tutorials/assembly.md
- tutorials/discord.md
- tutorials/editors/index.md
- tutorials/editors/pycharm.md
- tutorials/editors/vscode.md
- tutorials/getting_code_on_the_robot.md
- tutorials/python.md
create redirects to fix links for all the moved pages
> make redirects to fix broken links

- kit/batteries/index.md
> Add overlander battery guidance

- programming/motors.md
This makes type checking the docs much easier.
Fixes https://github.com/srobo/docs/issues/532
> Canonicalise around using Robot.sleep over time.sleep

- programming/leds.md
This makes these easier to copy/paste into code as well as making it easier to type-check the docs.
> Clarify the LED colour names

- _data/sidebar_tree.yaml
- simulator/simulator_programming.md
Update the docs for the simulator to match the new API and new robot layout.
(This gives hints about the new robot configuration, but we decided it's vague enough to keep public).
> Update docs for the simulator

- competitor_resources/markers.md
Adds link on resources page as well
> Add SR2024 marker PDF

- index.md
- simulator/index.md
We don't know if there will be one this year.
> Remove mentions of the virtual competition

- simulator/index.md
- simulator/setting_up_simulator.md
Update simulator top level page and installation page
Some simple changes to add clarity
> Update sim pages

- simulator/using_the_simulator.md
Missed from 40b410893fd660e9809ac8d9e10b8eb890db5b1c.
> Remove an indirect mention of the virtual competition

- competitor_resources/microgames.md
> Add link to SR2024 microgames

- simulator/setting_up_simulator.md
Just so this section doesn't launch straight into instructions.
> Add a short explainer on what the world simulation is

- .spelling
- _data/sidebar_tree.yaml
- robots_101/index.md
- robots_101/team_supervisor.md
- robots_101/tech_days.md
Newer teams won't know what these are, plus this gives us a handy page to reference from the event pages. Not completely sure if this fits into the Robots 101 section, but it seems as good a place as any.
> Document what a Tech Day is

- simulator/simulated_robot.md
As [reported by a team in Discord](https://discord.com/channels/1154145712943153252/1154145715518459950/1165378369702080532).
Tested via the keyboard robot.
> Fix ambiguous description of the simulated robot grabber servo

- simulator/simulated_robot.md
It actually returns a voltage, wich needs mapping to a distance
> Fix ultrasound units

- troubleshooting/index.md
The forums are dead, long live the forums
> Remove a reference to the forums

- .github/workflows/publish.yml
- Dockerfile
- Gemfile.lock
- README.md
- Rakefile
Bundle v1.x is pretty old now...
> Update to bundler v2

- _data/sidebar_tree.yaml
- competitor_resources/pre_kickstart_activities.md
- robots_101/programme_structure.md
The document isn't public yet, so we should hold off merging this until that's ready.
> Add a page about the pre-kickstart activities

- competitor_resources/markers.md
As generated in https://github.com/srobo/game-markers/pull/18
> Update marker PDF for SR2025

- competitor_resources/microgames.md
Kickstart is nearly upon us. This document is currently private and will be made public on the day.
See also https://github.com/srobo/tasks/issues/1365.
> Update the link to this year's microgames

- tutorials/index.md
Fixed the  kit assembly link to redirect to the assembly page rather than the basic motor control page
> Updated index.md

- .spelling
- tutorials/discord.md
Fixes https://github.com/srobo/tasks/issues/1471
Includes workaround for https://github.com/streetsidesoftware/cspell/issues/6582
> Canonicalise around 'blueshirt' not hyphenated

- .spelling
- tutorials/discord.md
Fixes https://github.com/srobo/tasks/issues/1471.
Includes workaround for https://github.com/streetsidesoftware/cspell/issues/6582 as we haven't upgraded cspell yet.
> Canonicalise around 'Blueshirt' as a proper noun

- .spelling
- _data/sidebar_tree.yaml
- rules/pit_rules.md
Closes srobo/tasks#1448
This updates the pit rules for 2025 and publishes them as part of the docs
> Add pit rules and update them for SR2025

- robots_101/programme_structure.md
This aims to better help rookies, be a target for related links and a place we can refer to for how to describe the virtual league in other media.
See also https://github.com/srobo/website/pull/599
> More detail on what the Virtual League is

- _data/sidebar_tree.yaml
- rules/safety_regulations.md
Much of the useful information is already in the rules. We don't really need to explain the explicit details of how to test.
> Update safety regulations page
