- images/logo.svg
I forgot to add this. Currently, when you look at the docs on a smaller screen, the logo is absent.
> Add the logo on mobile

- _includes/sidebar.html
While behind the reverse proxy, the sidebar currently redirects users out to srobo.github.io when they click on links which point to indexes of folders.
This doesn't fix the problem (which is Github Pages' fault), but it makes the sidebar usable.
> Add slashes to the end of index pages in the sidebar

- _includes/sidebar.html
There are some more links which, when clicked on behind the reverse proxy, redirect to srobo.github.io. This fixes those.
> Added slashes to the remaining redirecting links

- programming/sr/power/index.md
This is significanly more pleasant than using integer indices.
Note: this relies on sr-robot library changes which implement these constants (Change-Id: Ibb264b5264673f5097c007c54ee280f5c90464f6; https://saffron.studentrobotics.org/gerrit/2771).
> Document the constants for the power board outputs

- _sass/docs.scss
This was in the original patch, but appeared unneccesary in the new docs CSS.
It turns out that it is needed after all.
Change-Id: Ia1402a2d8d0496ac80e25a095d298f9e699d8a36
> Ensure tablet page images are size limited

- kit/wifi.md
The tablets have the old pre-chrome Android browser on them and it has
no features and supports nothing. We install 'Chrome Shell' onto the
tablets which does have features and does support things.
> You must use Chrome Shell on the tablet

- kit/index.md
While the previous generation of power board also contained the brain, the current generation kit has a separate ODRIOD as a brain.
> USB connections go to the ODRIOD

- programming/sr/vision/markers.md
- rules/index.md
This explains the rules are not yet published for the SR2019 competition.
> Remove references to the rules

- _sass/_syntax-highlighting.scss
Fixes code examples getting cut off when the lines are long, e.g.
> Allow horizontal scrolling on code blocks

- README.md
Version 2.x has a whole new file format which we don't want to switch over to yet as it would break a bunch of developer's setups.
> Require bundler 1.x

- Gemfile
This means that the gem will be installed on all platforms, avoiding the `Gemfile.lock` changing between platforms.
> Drop condition on depedency

- .editorconfig
It turns out you need to be explicit about this.
> Actually apply these rules to all files

- kit/motor_board.md
- kit/power_board.md
- kit/servo_board.md
These repositories were recently moved from legacy cgit to github.
> Update URLs of board firmware and hardware repositories

- kit/index.md
This is what the kit will contain. 
The change in wire is because I witnessed a lot of teams using .5mm wire for power. So by providing thick(1mm) power wire and thin (.5mm) signal wire, it makes it a lot easier for them. Also by providing more it makes it less likely they'll use the signal wire.
Also new USBs all round.
> Updates for sr2020 kickstart

- competition-simulator/index.md
Resolves https://github.com/srobo/competition-simulator/issues/89
Webots supports 3.7 on all platforms so we should be explicit in the documentation about this
> Specify version 3.7

- competition-simulator/index.md
Webots support is a little strange.
This PR also commits to 3.7 in the event, which is supported on all platforms.
Further fixes https://github.com/srobo/competition-simulator/issues/89
Fixes https://github.com/srobo/competition-simulator/pull/92
Fixes https://github.com/srobo/competition-simulator/pull/91
> Correct supported versions of Python

- competition-simulator/index.md
- programming/python/libraries.md
We've decided to allow the inclusion of libraries, so document a way that teams can request them.
See Slack conversation starting at https://studentrobotics.slack.com/archives/CD6C80TRD/p1592561812008400.
> Let competitors request external libraries in the simulator

- _data/sidebar_tree.yaml
- _sass/docs.scss
- competition-simulator/index.md
- competition-simulator/programming/index.md
- competition-simulator/programming/time.md
- programming/sr/index.md
This pulls the time documentation onto its own page and then expands it to include detailed documentation for the `ManualTimestepRobot` introduced by https://github.com/srobo/competition-simulator/pull/158.
> Expand documentation of time

- competition-simulator/programming.md
This changed a while back, so remove the warning about it being unsuitable.
> The IDE now supports developing for the simulator

- simulator/index.md
The current development version does, which is why the docs say that it's supported, however the latest release doesn't yet have that support.
See https://github.com/cyberbotics/webots/issues/2469.
> It turns out that Webots doesn't (yet) support Python 3.9

- simulator/programming/index.md
> Drop overlooked reference to the dead ManualTimestepRobot class

- programming/sr/radio/index.md
This is deliberately vague on exactly how often this happens, so that we can easily change that if needed.
> Clarify territory transmissions

- simulator/programming/index.md
Sonar type distance sensor will only detect an object if the pulse contacts the face within a 45 degree cone about the normal.
See https://cyberbotics.com/doc/reference/distancesensor#sonar-sensors for more details.
> Distance sensors don't work at extreme angles

- simulator/index.md
Do not merge until module 3.
We're now changing the version requirement. It'll still work on older ones, but we want to encourage using new ones, as it fixes a number of issues.
> Specify the version of webots used

- programming/sr/radio/index.md
This reverts commit c1545cfe22d75ec0ae6607e41a7ac6b40c81075f.
We're not doing this anymore.
> Revert "Mention the new 'TargetInfo.locked' attribute"

- _data/sidebar_tree.yaml
- team_admin/index.md
The sidebar is manually configured and the link needs to be deleted from it manually
> Remove Shipping link from sidebar.yml

- .github/workflows/validate.yml
- Gemfile
- Gemfile.lock
- Rakefile
- _includes/footer.html
- _includes/navigation.html
- kit/wifi.md
- programming/python/index.md
- programming/python/libraries.md
- team_admin/user_accounts.md
- troubleshooting/index.md
- tutorials/python.md
Contributes towards https://github.com/srobo/tasks/issues/701.
Contrary to https://github.com/srobo/website/pull/318, I've used `{{ site.url }}` rather than our literal domain name. This feels like it might be slightly nicer here, though there is some room for confusion between it and `{{ site.baseurl }}`. Would be good to get feedback on this -- if it's preferred I'll update the website repo to do the same.
> Add html-proofer as a validation mechanism

- _data/sidebar_tree.yaml
These are simulator only and we're not shipping the simulator this year.
> Hide the Radio & Compass docs

- _data/sidebar_tree.yaml
- kit/index.md
- kit/safety-regulations.md
Move some of the details usually put in the appendices of the rules into the docs, where it's easier to reference. 
See https://studentrobotics.org/docs/resources/2019/rulebook.pdf
This is mostly useful for the kit disclaimer forms, so we can reference these bits of documentation without releasing a full rulebook.
> Kit details from rules

- _includes/footer.html
- programming/editors/index.md
This removes the remaining visible IDE references from the docs.
The remaining references aren't visible and/or need more general updates than it's easy to do in this PR. Notably:
- https://github.com/srobo/docs/pull/268
- the WiFi page which needs deeper updates
> Remove more IDE references

- _data/sidebar_tree.yaml
- kit/index.md
- kit/power_board.md
- troubleshooting/index.md
- troubleshooting/python.md
We're not shipping WiFi yet, so remove mentions of it from the docs.
This leaves the dedicated WiFi page, but hides it from the sidebar. All the other mentions are removed. Hopefully this should be easy enough to revert when the WiFi does ship.
> Remove mentions of WiFi that isn't shipping (yet)

- _sass/messages.scss
Content within a div that has markdown enabled is wrapped in a p tag which means our custom styles were overwritten.
Fixes #279
> Override paragraph styling inside message boxes

- resources/kit/ruggeduino-fw.ino
In order to match the version that we flash to boards, this should be `1`.
This needs to be changed as the latest version of the kit software actually verifies that the firmware versions are supported before proceeding.
> Update the current Ruggeduino FW_VER to1

- Rakefile
- _data/sidebar_tree.yaml
Fixes https://github.com/srobo/docs/issues/294.
This adds validation that the sidebar urls and kit versions are in the right formats.
The validation for the sidebar urls focusses more on the things which are harder to spot as the chances of making an accidental change which breaks the sidebar without noticing are fairly high.
> Validate sidebar & kit version data

- kit/ruggeduino.md
This updates the links to use versions hosted by the internet archive as the original manufacturer no longer hosts these pages.
I _think_ the internet archive allows this; I had a quick skim of their terms of service and couldn't see anything otherwise (searches for "link" didn't highlight anything).
Fix https://github.com/srobo/docs/issues/113.
> Link to historic ruggeduino docs

- programming/sr/vision/index.md
The naming of these objects also seems somewhat confusing -- _lots_ of these are three dimensional coordinates, so the one called `ThreeDCoordinate` should probably be called `CartesianCoordinate`, since that's what it actually is. Obviously that's an API change rather than something we can do now.
> Fix link to the ThreeDCoordinate section

- programming/sr/vision/index.md
It's not currently clear how the diagram maps to the variables; this pull request changes that.
> Add clarification of 'spherical' variables

- kit/safety-regulations.md
This fixes https://github.com/srobo/docs/issues/324 by copying in the regulations from the last version of the published rules prior to the move to HTML format. This therefore post-dates the changes to the kit with which the current regulations are incompatible with (surprising an issue which appears to have already been present but missed in https://github.com/srobo/docs/pull/256) but pre-dates the removal of the regulations from the rulebook.
The first commit here is a pure copy of the text from the rules, specifically as they were in the [SR2020.5](https://github.com/srobo/rules/releases/tag/SR2020.5) (https://github.com/srobo/rules/commit/00e4ede22f21b2c8e99d5aa5928fe60b4e1d2cad), converted with `pandoc`.
The second change clarifies the placement of the power switch, something which I …
> Fix Safety Regulations

- kit/index.md
Notably:
- Remove odroid power cable
- Remove references to odroid
Notably, we're not shipping any additional camcons for the KCH - there are enough with the current number.
This doesn't document or note the KCH - that'll happen later.
> Update kit list for SR2023

- images/content/kit/kit_assembly.svg
change some lines from black to grey to allow for it to be seen when against a black background
> Fix coloring of wires and lines in assembly diagram

- _data/kit_versions.yml
- _includes/updates-table.html
- kit/brain_board/updates.md
- Add check for 0 updates being available.
- Download images from GitHub Releases
- Remove licence information. We are going to stop publishing it as the robot-image repo has the information.
> Get Brain Updates page ready for SR2023

- programming/sr/compass/index.md
- programming/sr/radio/index.md
While this is a little unusual for markdown these days, having a consistent style is better than a mixture as it enables easier searching for code blocks.
> Standardise around 5 tilde characters (~)

- _config.yml
This won't be present when GitHub Pages builds the site, so having it present is merely likely to create confusion (as well as slow down the build locally/in CI).
> Ingore node_modules when building the site

- simulator/programming/index.md
This is largely stolen from https://github.com/srobo/docs/pull/191, though placed in a location that more clearly applies to the whole simulator rather than just the radio.
Fixes https://github.com/srobo/docs/issues/190
Replaces https://github.com/srobo/docs/pull/191
> Document the noise we add to the simulator

- Rakefile
- resources/troubleshooter/data.json
This adds validation of the internal question links and of the urls that the troubleshooter contains which point to pages within the docs.
We cannot reasonably validate links outside the docs, so we don't attempt to.
Previously the links had an extra `docs/` in them, which meant that none of them worked either locally or in production.
> Add validation of the interactive troubleshooter and fix urls issue

- kit/brain_board/index.md
This is here mostly so we can mention that their computer won't be able to read the data, which would otherwise be a scary warning from their computer.
Fixes https://github.com/srobo/docs/issues/291
> Tell users to safely eject the SD card after flashing

- kit/motor_board.md
This draws its information from https://github.com/srobo/docs/pull/98 but starts afresh to effect a more minimal change.
Fixes https://github.com/srobo/docs/issues/96
Replaces https://github.com/srobo/docs/issues/98
> Document what fault cause the motor board fault LED to light

- _data/sidebar_tree.yaml
- programming/sr/leds/index.md
I've opted to name this document after the LEDs it controls, rather than the board where those LEDs are hosted, to follow the naming pattern of the "motors", "servos" (etc.) docs which do the same for the other boards. This should be easy to change if naming this after the host board would be preferred.
This is based on the current state of the API integration in https://github.com/srobo/sr-robot3/pull/60 and with reference to [`kch.py` in J5](https://github.com/j5api/j5/blob/main/j5/boards/sr/kch.py), so may not be quite how this is intended to function. Hopefully there's a useful starting point here though.
Fixes https://github.com/srobo/docs/issues/358
> Document how to use the LEDs on the KCH HAT

- programming/sr/leds/index.md
Identified by pandoc, this heading shares its identifier (#leds) with the page title.
> Remove duplicate heading

- simulator/index.md
This is mostly updating for Webots R2022b, however the underlying simulation is not ready yet so we don't have a world file to publish. This change is mostly so we can link to this page without giving misleading information about the state of the simulator.
> Updates ahead of the SR2023 simulator

- _sass/docs.scss
- kit/assembly.md
Think we could still make this better but think there are more important things to spend time on right now :)
<details>
<summary>Desktop</summary>
</details>
<details>
<summary>Mobile (Portatit)</summary>
</details>
<details>
<summary>Mobile (Landscape)</summary>
</details>
> Make Kit Assembly video less square

- tutorials/basic_motor_control.md
There are various fixes here, notably:
- there is no longer a separate battery cable
- the power board current limits are different (and not all fuse based)
- Python `for` & `range` are quite different (and don't need to involve `list`s)
See commits for more.
Fixes https://github.com/srobo/docs/issues/93, though it might still be useful for someone to run through the tutorial through with actual hardware in front of them.
> Update motor tutorial for the latest Kit & Python

- .spelling
- kit/brain_board/index.md
- kit/wifi.md
We need to document how the `robot-settings.toml` file is created and what the settings in it mean.
This is the file that students need to edit to customise their WiFi password. It is automatically generated if a USB drive is inserted containing a `robot.py`
> Add docs on the robot-settings.toml file

- simulator/index.md
Add a link for the 2023 release of the competition simulator
Fixes: https://github.com/srobo/tasks/issues/969
> Add link for 2023 simulator release

- simulator/index.md
Various changes to improve the first-run UX.
Note: using `import sys; print(sys.executable)` is untested on platforms other than Linux (I don't have others to hand), but it seems highly likely to work.
> Improve simulator setup

- tutorials/python.md
Python 3 division does much more what you'd expect so this gotcha no longer applies.
> Remove link about old Python division

- _includes/updates-table.html
Fix the link on the website to the robot image on the release on git
> Fix git link url

- programming/sr/vision/markers.md
A markers' size is actually the size of the marker itself (the black bit) rather than the grey border as it was with Koki.
> Fix marker size description

- programming/getting_code_on_the_robot.md
Reference of said context menu:
> Update "Getting Code on the Robot" to include icon reference for Windows 11 context menu

- Gemfile
- Gemfile.lock
- Rakefile
This ports the changes from https://github.com/srobo/website/pull/473.
This isn't officially supported by Jekyll and is a bit hacky, so I'm deliberately not documenting the support, however as recent Ubuntu versions now ship with Ruby 3 (not 2.7) and Jekyll isn't showing any signs of moving towards supporting Ruby 3 we're not left with many alternatives.
> Support Ruby 3

- Dockerfile
Without this it sees the git repo as being owned by the external user, which is different to the root user that is running in the container. This seems to mostly impact CI, where the submodules aren't cloned by default.
> Teach git in the docker container to trust our git repo

- simulator/index.md
This release focusses on improvements for match running and is released mostly so competitors can run the same code as is planned to be used for the virtual competition. The only competitor facing change is a compatibility alias of a property.
> Update the simulator to sr2023.5

- programming/sr/index.md
It's actually a `RobotMode` enum. This is exported correctly from `sr.robot3`.
> `R.mode` isn't a string

- kit/brain_board/python_libraries.md
- tutorials/setting_up_simulator.md
Libraries synced between the image and simulator, python libs page updated to reflect this
Simulator libraries https://github.com/srobo/competition-simulator/blob/main/libraries.txt
Robot image libraries https://github.com/srobo/robot-image/blob/main/libraries.txt
Robot image requirements https://github.com/srobo/robot-image/blob/main/requirements.txt
> Update page on python libraries

- Rakefile
- _data/kit_versions.yml
- _includes/updates-list.html
- kit/brain_board/python_libraries.md
Also change yaml to define link. This allows for flexibility if something about the link changes (we had this issue last year). It also pulls all the hardcoded data into the single yaml file instead of being spead between the two files.
> Update img release for this years initial image release

- programming/cheat_sheet.md
> SR2024 - Update Section - API Quick Reference

- tutorials/setting_up_simulator.md
This deliberately breaks the link to the simulation files as we have not yet released a version for SR2024, so any link would be incorrect relative to the documented versions.
See also #506.
> Update Python & Webots versions the simulator uses

- _data/sidebar_tree.yaml
- tutorials/assembly.md
- tutorials/basic_motor_control.md
- tutorials/getting_code_on_the_robot.md
- tutorials/index.md
- tutorials/python.md
- kit assembly page
- getting started with python
- getting code on the robot
- basic motor control
> Update some of the tutorial pages

- programming/power.md
This makes type checking the docs much easier.
Fixes https://github.com/srobo/docs/issues/531
> Canonicalise around Robot instances being 'robot'

- tutorials/editors/vscode.md
I'm assuming that all the SR2024 kit versions now support this.
> Remove a redundant kit software version warning

- simulator/setting_up_simulator.md
We've not released these yet and may not do so before Kickstart.
This is needed to unblock https://github.com/srobo/team-emails/pull/159
> Hide the links to download the simulation files

- tutorials/python.md
From the context it looks like this was previously comparing Python 2's `raw_input` and `input` functions, and that this was missed during the upgrade to Python 3. Drop the comparison and explicitly parse the inputs to numbers to let the reader focus on the task at hand (computing the average).
Fixes https://github.com/srobo/docs/issues/533
> Fix confused usage of `input` in the Python tutorial

- simulator/simulated_robot.md
Link back to the programming page for each of the robot components of the simulated robot.
This has a lot of repetition to better enable the page as a quick reference
> Make simulated robot docs more helpful

- index.md
- simulator/index.md
- simulator/using_the_simulator.md
> Add back virtual competition documentation for SR2024

- programming/index.md
- tutorials/getting_code_on_the_robot.md
Following a conversation in Discord, I realised we don't make it especially clear that the code shouldn't (ie couldn't) be run from your computer, and instead should be edited there but run on the robot.
This PR tries to clear that up, mostly by littering references to it throughout the relevant parts of the docs.
> Make it clearer that code runs on the robot

- kit/brain_board/python_libraries.md
We occasionally have competitors ask whether the standard library is available - we should clarify explicitly that it is.
I also intentionally reference "Python 3.11" rather than just "Python", to include the version number on this page.
> Reference standard library when talking about available libraries

- simulator/setting_up_simulator.md
This release includes:
- allows LEDs to be set right away
- locks simulator components, avoiding accidental movement
- fixes to a lighting bug
- improves windows competition-mode match running
https://github.com/srobo/competition-simulator/releases/tag/sr2024.2
> Update the simulator to sr2024.2

- kit/arduino.md
- kit/brain_board/index.md
- kit/motor_board.md
- kit/power_board.md
- kit/servo_board.md
We've had links the other way for a long time, but not this way around. Adding these makes the docs more easily navigable.
> Link from the hardware docs to the software docs

- programming/arduino/index.md
A competitor asked about this in Discord recently which made me realise we don't have this linked obviously. The only mention is on the page about extending the SR firmware, and then in the context of using it as a starting point for other firmware.
> Add an easy link back to the original arduino firmware

- README.md
People count from one, so should our lists.
> Lists start from one

- .github/workflows/publish.yml
This is copied over from the website repo, which now has these in place.
See https://github.com/srobo/website/pull/570 & https://github.com/srobo/website/pull/573.
Builds on https://github.com/srobo/docs/pull/594 which removes the feed and makes the build deterministic.
> Add support for PR diff comments vs the deployed version

- .github/workflows/publish.yml
- README.md
GitHub have removed v1 from their CI images, see https://github.com/actions/runner-images/issues/9692.
I thiiink this is what was already expected since the compose file is labelled as v2, though I don't know enough about docker compose to be sure.
> Move to using Docker Compose v2 explicitly

- .github/workflows/publish.yml
Something changed recently in how actions/upload-artifact creates its archives, such that symlinked files behaved differently under that action than under actions/upload-pages-artifact. This broke our diffing logic.
Move to using the same upload approach for both the local and reference main builds, to avoid spurious errors.
> Use a consistent mechanism to upload our reference build

- .github/workflows/publish.yml
- _config.yml
This ensures that key-ordering changes, which don't affect the semantics of the file, don't create diff noise (such as that in https://github.com/srobo/docs/pull/597#issuecomment-2264369027).
Also exclude some build-time JSON files from the output.
Builds on #600 to pick up that fix.
> Normalise the JSON redirects file before diffing

- resources/kit/arduino-fw.ino
Updated from https://github.com/srobo/ruggeduino-fw/tree/ed03aa2307758462736edbaf200cc3880bd7efec
> Update arduino firmware file to support ultrasound

- _data/sidebar_tree.yaml
- robots_101/index.md
- robots_101/programme_structure.md
- robots_101/team_supervisor.md
This extends the supervisor page and adds a new page about the overall programme structure. The goal here is to address the key aspects of https://github.com/srobo/tasks/issues/1357, though to fully complete that we'll also need to actually get these docs in front of supervisors early in the cycle.
This may also go some way towards other issues linked from that one, though I don't think fully addresses any single one of them. Again this is partly about getting the information in other places (though hopefully this is now something we can more easily/usefully link to).
As part of this change I've also linked to the team-supervisor ("Running a team") page from the signup form for SR2025. Ideally we'd include this change before that goes live, but even as it stands it's a useful resource for …
> Provide more information for supervisors

- programming/vision/index.md
Documents the change implemented in https://github.com/srobo/sr-robot3/pull/19
> Update camera docs for new API

- kit/return.md
We often send teams details of kit return when they drop out, but it's probably a good idea to have it generally available.
This information was derived from previous competitions, and the [Kit Shipping](https://studentrobotics.org/runbook/kit/logistics/transport/) pages of the runbook.
> Add documentation for kit return

- _data/sidebar_tree.yaml
- kit/index.md
This makes the loan nature even clearer as people will more easily know what they're getting themselves into.
> Add some links to the kit return page

- Gemfile
- Gemfile.lock
The related bug has since been fixed (and we appear to have already pulled it in).
See also:
- https://github.com/srobo/competition-website/pull/61
- https://github.com/srobo/style/pull/53
- https://github.com/srobo/website/pull/585
> Drop explicit webrick dependency

- robots_101/tech_days.md
Now that we're linking to this page a bit more from various places, having an easy way from here to the events for the current year seems like it's useful.
> Link sooner to the list of Tech Days for the current year

- README.md
- competitor_resources/pre_kickstart_activities.md
- programming/arduino/sr_firmware.md
- programming/robot_api/index.md
- robots_101/design.md
- robots_101/programme_structure.md
- tutorials/getting_code_on_the_robot.md
- tutorials/python.md
- tutorials/update_brain.md
Due to lack of knowledge, disability, additional needs, or other reasons I don't think we can call any task simple. This PR changes most references to simple to be more neutral by removing the word or rewording the sentence.
> Remove or reword most references to "simple" tasks

- _data/sidebar_tree.yaml
- robots_101/events.md
- robots_101/index.md
- robots_101/post_kickstart.md
- robots_101/programme_structure.md
- robots_101/team_supervisor.md
- robots_101/tech_days.md
This mostly serves as a place to document that we don't require the primary contact to be the person who brings a team to our events, which is something that we're asked every year. We've pretty much always had the same policy, however tend to need to re-evaluate it every time it's asked as we haven't written it down.
Fixes https://github.com/srobo/tasks/issues/1475
> Add general information about our events

- tutorials/getting_code_on_the_robot.md
Notably it was previously too easy to get the file name wrong or miss the importance of spelling it exactly as provided.
> Clarify the instructions for getting code on the robot

- .spelling
- programming/arduino/custom_firmware.md
- programming/arduino/sr_firmware.md
- programming/cheat_sheet.md
- programming/leds.md
- programming/motors.md
- programming/power.md
- programming/robot_api/comp_mode.md
- programming/robot_api/index.md
- programming/servos.md
- programming/vision/index.md
- tutorials/basic_motor_control.md
It's bad practice, and should be explicit where the values came from.
This also explicitly talks about enums, what they are, and how to use them (correctly and incorrectly).
> Avoid wildcard imports and mention enums

- _data/sidebar_tree.yaml
- robots_101/programme_structure.md
- tutorials/code_submitter.md
While it's pretty easy to use, having somewhere that we can point people rather than needing to either include these instructions all over the place (and make them up each time) is very useful.
Builds on https://github.com/srobo/docs/pull/653 to avoid conflicts.
> Document use of the code-submitter

- tutorials/discord.md
> Discord updates

- programming/robot_api/index.md
- simulator/using_the_simulator.md
These methods exist, and are incredibly useful, but aren't documented.
> Document `robot.sleep` and `robot.time`

- kit/index.md
- kit/return.md
Letter 'x' is not a times symbol.
> Use a better times symbol

- _data/kit_versions.yml
- _includes/updates-list.html
- kit/brain_board/robot_os.md
> Add SR2025 image to OS updates page
